Repository wp-graphql/wp-graphql-jwt-authentication, pull requests merged in 2020-02, with the labels that each got.

#72 #69 - JWT Tokens could not be returned after regiserUser mutation
  src/Auth.php
  src/ManageTokens.php
Labels: bug

#75 #69 - Backward Compatibility fixes for playing nice with WPGraphQL for WooCommerce
  src/Auth.php
  src/ManageTokens.php
Labels: bug

#78 Docs/add all mutations
  README.md
  src/Auth.php
Labels: Documentation

#81 Release/v0.4.0
  .gitignore
  README.md
  src/Auth.php
  src/ManageTokens.php
  tests/_output/c3tmp/codecoverage.clover.xml
  tests/_output/c3tmp/codecoverage.serialized
  tests/_output/c3tmp/codecoverage.tar
  tests/_output/coverage.wpunit.cov
  tests/_output/coverage.xml
  tests/_output/functional.remote.coverage.xml
  tests/_output/functional.remote.coverage/.css/bootstrap.min.css
  tests/_output/functional.remote.coverage/.css/nv.d3.min.css
  tests/_output/functional.remote.coverage/.css/style.css
  tests/_output/functional.remote.coverage/.fonts/glyphicons-halflings-regular.eot
  tests/_output/functional.remote.coverage/.fonts/glyphicons-halflings-regular.svg
  tests/_output/functional.remote.coverage/.fonts/glyphicons-halflings-regular.ttf
  tests/_output/functional.remote.coverage/.fonts/glyphicons-halflings-regular.woff
  tests/_output/functional.remote.coverage/.fonts/glyphicons-halflings-regular.woff2
  tests/_output/functional.remote.coverage/.js/bootstrap.min.js
  tests/_output/functional.remote.coverage/.js/d3.min.js
  tests/_output/functional.remote.coverage/.js/file.js
  tests/_output/functional.remote.coverage/.js/holder.min.js
  tests/_output/functional.remote.coverage/.js/html5shiv.min.js
  tests/_output/functional.remote.coverage/.js/jquery.min.js
  tests/_output/functional.remote.coverage/.js/nv.d3.min.js
  tests/_output/functional.remote.coverage/.js/respond.min.js
  tests/_output/functional.remote.coverage/dashboard.html
  tests/_output/functional.remote.coverage/index.html
  tests/_output/functional.remote.coverage/src/Auth.php.html
  tests/_output/functional.remote.coverage/src/Login.php.html
  tests/_output/functional.remote.coverage/src/ManageTokens.php.html
  tests/_output/functional.remote.coverage/src/RefreshToken.php.html
  tests/_output/functional.remote.coverage/src/dashboard.html
  tests/_output/functional.remote.coverage/src/index.html
  tests/_output/functional.remote.coverage/wp-graphql-jwt-authentication.php.html
  wp-graphql-jwt-authentication.php
Labels: Release
